# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9873bebb0d7eba0c03cbbee0b97c7abc9cb540cf7314dbd9545e81dffe6550b5334c1c67cebe12d60811192d56e7a2870d50cfcc8d9fb4204b796a660f78c584

test:
  secret_key_base: 74faf516301218042da1bc14a6494312d6c1caae14fd5f6e74dd1d6ffb9e84847c34924087ba341240d6c048aca9fbc111b2075efcec7f8a922b4240f24b29ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
